# -*- coding: utf-8 -*-
"""MYEUGiftReceiving.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1swDRgNeQ7TOVFcHKcFEDwBYyNRk19vSI
"""

import streamlit as st
import requests
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime

# --- KẾT NỐI GOOGLE SHEETS TỪ SECRETS ---
@st.cache_resource
def get_gsheets_client():
    creds_dict = st.secrets["gcp_service_account"]
    creds = Credentials.from_service_account_info(
        creds_dict,
        scopes=[
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive"
        ]
    )
    return gspread.authorize(creds)

# Điền ID của file Google Sheets vào đây (lấy trên thanh URL của trình duyệt)
SHEET_ID = "1ce2iU7qzr9PUoGMorlIaNMYb3KDGizmhiIRquWN8dOE"

# --- HÀM UPLOAD ẢNH LÊN IMGBB ---
def upload_image_to_imgbb(image_bytes):
    url = "https://api.imgbb.com/1/upload"
    payload = {
        "key": st.secrets["IMGBB_API_KEY"]
    }
    files = {
        "image": image_bytes
    }
    response = requests.post(url, data=payload, files=files)
    if response.status_code == 200:
        return response.json()["data"]["url"]
    else:
        return None

# --- CACHE & STATE QUẢN LÝ ĐĂNG NHẬP ---
if 'logged_in' not in st.session_state:
    st.session_state['logged_in'] = False
if 'staff_name' not in st.session_state:
    st.session_state['staff_name'] = ""

# --- CẤU HÌNH GIAO DIỆN & CSS ---
st.set_page_config(page_title="Ghi Nhận Quà Sự Kiện", page_icon="🌻", layout="centered")

css = """
<style>
    @media max-width: 768px {
        .main-title { font-size: 24px !important; line-height: 1.3 !important; white-space: nowrap !important; }
    }
    .main-title {
        background: linear-gradient(to right, #8B0000, #CC7722, #FFB300);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: left; font-size: 32px; font-weight: bold; margin-bottom: 20px;
    }
    .question-text {
        background: linear-gradient(to right, #D81B60, #8E24AA);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-size: 18px; font-weight: 600; margin-bottom: 10px;
    }
    .stButton > button[kind="primary"] {
        background: linear-gradient(to right, #D81B60, #8E24AA) !important;
        color: white !important; border: none !important;
    }
</style>
"""
st.markdown(css, unsafe_allow_html=True)

# --- MÀN HÌNH ĐĂNG NHẬP ---
if not st.session_state['logged_in']:
    st.markdown('<div class="main-title">HỆ THỐNG GHI NHẬN<br>NHẬN QUÀ TẶNG MYÊU SHOW</div>', unsafe_allow_html=True)
    password = st.text_input("Vui lòng nhập mã truy cập của bạn:", type="password")

    # M tạo 1 danh sách các pass hợp lệ ở đây (ví dụ cấp cho An, Trang, Phuong)
    danh_sach_pass_hop_le = {
        "PassCuaAn2026": "An",
        "TrangNhanQua!": "Trang",
        "0519": "Phương"
    }

    if st.button("Vào hệ thống", type="primary"):
        # Kiểm tra xem pass nhập vào có nằm trong danh sách không
        if password in danh_sach_pass_hop_le:
            # Lấy tên staff tương ứng với pass đó
            st.session_state['staff_name'] = danh_sach_pass_hop_le[password]
            st.session_state['logged_in'] = True
            st.rerun()
        else:
            st.error("Sai password rồi nha!")

# --- MÀN HÌNH CHÍNH (SAU KHI ĐĂNG NHẬP) ---
else:
    col1, col2 = st.columns([8, 2])
    with col2:
        if st.button("Đăng xuất"):
            st.session_state['logged_in'] = False
            st.session_state['staff_name'] = ""
            st.rerun()

    st.markdown('<div class="main-title">NHẬN QUÀ ANH THIÊN MINH<br>TỪ 🌻🤍 MYÊU 🤍🌻</div>', unsafe_allow_html=True)
    st.write(f"Đang trực hệ thống: **{st.session_state['staff_name']}**")
    st.divider()

    st.markdown('<div class="question-text">Mình xin số ghế của bạn nha</div>', unsafe_allow_html=True)
    seat_num = st.text_input("Nhập số ghế (VD: C6)")
    photo = st.camera_input("Chụp lại tấm hình")

    if st.button("Đã nhận quà", type="primary"):
        if not seat_num:
            st.warning("Bạn quên nhập số ghế kìa!")
        elif photo is None:
            st.warning("Vui lòng chụp lại hình làm chứng minh nha!")
        else:
            # Hiển thị loading spinner cho staff biết hệ thống đang xử lý
            with st.spinner("Đang lưu dữ liệu lên hệ thống..."):
                try:
                    # 1. Bắn hình lên ImgBB lấy link
                    img_url = upload_image_to_imgbb(photo.getvalue())

                    if img_url:
                        # 2. Bắn data vào Google Sheets
                        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

                        client = get_gsheets_client()
                        sheet = client.open_by_key(SHEET_ID).worksheet("Sheet1")

                        # Dùng append_row để thêm 1 dòng mới tinh, không sợ bị đè data của nhau
                        sheet.append_row([timestamp, st.session_state['staff_name'], seat_num.upper(), img_url])

                        st.success(f"🎉 Hệ thống đã ghi nhận thành công cho ghế {seat_num.upper()}!")
                    else:
                        st.error("Lỗi khi tải hình ảnh lên server. Vui lòng thử lại!")
                except Exception as e:
                    st.error(f"Có lỗi xảy ra: {e}")
